INSERT INTO teamcreziosp.planos
(nome,qtd_aulas,taxa_matricula,kimono,ferias,convidado,transferivel)
VALUES
('WHITE BELT',1,99,479,DEFAULT,DEFAULT,DEFAULT),

('BLUE BELT',2,99,479,DEFAULT,DEFAULT,DEFAULT),

('PURPLE BELT',0,99,479,DEFAULT,DEFAULT,DEFAULT),

('KIDS',1,99,319,DEFAULT,DEFAULT,DEFAULT),

('BLACK BELT',0,DEFAULT,DEFAULT,1,1,1),

('SUPER KIDS',0,DEFAULT,DEFAULT,1,1,1),

('SINGLE +',2,DEFAULT,DEFAULT,1,1,1),

('TRIPLE +',2,DEFAULT,DEFAULT,1,1,1),

('SINGLE',2,99,DEFAULT,DEFAULT,DEFAULT,DEFAULT),

('TRIPLE',2,99,DEFAULT,DEFAULT,DEFAULT,DEFAULT);
